export const SELECTORS = {
  BODY: 'body',
  OVERLAY: '.overlay',
  MODAL: '.modal',
  GIFTS_LIST: '.gifts__list',
  SCROLL_TOP: '.scroll-top',
  SLIDER_TRACK: '.slider__track',
  SLIDER_BTN_LEFT: '.slider__btn--left',
  SLIDER_BTN_RIGHT: '.slider__btn--right',
  FILTER_BUTTON_ALL: '.filter ul li:nth-child(1)',
  FILTER_BUTTON_WORK: '.filter ul li:nth-child(2)',
  FILTER_BUTTON_HEALTH: '.filter ul li:nth-child(3)',
  FILTER_BUTTON_HARMONY: '.filter ul li:nth-child(4)',
  HEADER_BURGER_CHECKBOX: '.header__burger-checkbox',
  BURGER_MENU: '.burger-menu',
  BURGER_MENU_ID: '#burger-menu',
  HEADER_NAV_LINK: '.header__nav-link',
  COUNTDOWN_DAYS: '.days',
  COUNTDOWN_HOURS: '.hours',
  COUNTDOWN_MINUTES: '.minutes',
  COUNTDOWN_SECONDS: '.seconds',
};
